### ISSUE TITLE
Join everyone to the repo

### ISSUE THREAD

**Issue by olendorf** [psu-libraries/library_data_services_model#2]
### Requirements 

- [x] Join everyone to the repo 

- [x] Send email

- [x] Rama invited

- [x] Stephen invited 

- [x] Patricia invited 

- [x] Nathan invited 

- [x] Robyn invited

**Comment by olendorf** [comment]
I think people are joined, and email sent. Moving to Needs review for people to sign off on.

**Comment by RJV5174** [comment]
How do you sign of an issue?? By commenting?

**Comment by olendorf** [comment]
@RJV5174 Sort of. There is one assignee. But you can add other participants by commenting. Thats how I usually get multiple participants on an issuel

**Comment by RJV5174** [comment]
Okey got it. I think the others who are not checked in have not yet logged on.

**Comment by olendorf** [comment]
Yeap, thats fine. I'll send an email tomorrow if need be.

**Comment by rreed123** [comment]
Looks like I'm in.

**Comment by olendorf** [comment]
Thanks all. closing the issue now.
